all:
	mipsel-linux-gcc -g main.c -o ram_speed -lSDL_image -lSDL -lSDL_ttf -I/home/steward/Github/gh_retrogame_toolchain/mipsel-linux-gcc/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL
clean:
	rm -rf ram_speed
