// Automatically generated by build process.

#ifndef BUILD_INFO_HH
#define BUILD_INFO_HH

#include <string>

#define ASM_X86 0
#define ASM_X86_32 0
#define ASM_X86_64 0
#define PLATFORM_DINGUX 1
#define PLATFORM_GP2X 0
#define PLATFORM_MAEMO5 0
#define HAVE_16BPP 1
#define HAVE_32BPP 0
#define MIN_SCALE_FACTOR 1
#define MAX_SCALE_FACTOR 1

namespace openmsx {

static const bool OPENMSX_BIGENDIAN = false;
static const bool OPENMSX_UNALIGNED_MEMORY_ACCESS = false;
static const bool OPENMSX_SET_WINDOW_ICON = true;
static const std::string DATADIR = "derived/mipsel-dingux-opt-3rd/bindist/install/share";
static const std::string BUILD_FLAVOUR = "opt";

} // namespace openmsx

#endif // BUILD_INFO_HH
