// Automatically generated by build process.

#ifndef COMPONENTS_HH
#define COMPONENTS_HH

#include <string>

#define COMPONENT_CORE 1
#define COMPONENT_GL 0
#define COMPONENT_LASERDISC 0
#define COMPONENT_AO 1

namespace openmsx {

static const std::string BUILD_COMPONENTS = "AO CORE";

} // namespace openmsx

#endif // COMPONENTS_HH
