# Automatically generated by build system.
# Non-empty value means found, empty means not found.
HAVE_AO_H:=true
HAVE_AO_LIB:=true
AO_CFLAGS:=
AO_LDFLAGS:=-lao
HAVE_PNG_H:=true
HAVE_PNG_LIB:=true
PNG_CFLAGS:=-I/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/libpng16
PNG_LDFLAGS:=-L/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib -lpng16
HAVE_SDL_H:=true
HAVE_SDL_LIB:=true
SDL_CFLAGS:=-I/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
SDL_LDFLAGS:=-L/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib -lSDL -lpthread
HAVE_SDL_TTF_H:=true
HAVE_SDL_TTF_LIB:=true
SDL_TTF_CFLAGS:=-I/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/freetype2
SDL_TTF_LDFLAGS:=-lSDL_ttf
HAVE_TCL_H:=true
HAVE_TCL_LIB:=true
TCL_CFLAGS:=-DPACKAGE_NAME=tcl -DPACKAGE_TARNAME=tcl -DPACKAGE_VERSION=8.5 -DPACKAGE_STRING=tcl\\\ 8.5 -DPACKAGE_BUGREPORT= -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_SYS_PARAM_H=1 -DTCL_CFGVAL_ENCODING=iso8859-1 -DSTATIC_BUILD=1 -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(hidden\)\)\) -DTCL_SHLIB_EXT=.so -DTCL_CFG_OPTIMIZED=1 -DTCL_CFG_DEBUG=1 -DTCL_TOMMATH=1 -DMP_PREC=4 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_TYPE=long\ long -DHAVE_STRUCT_STAT64=1 -DHAVE_OPEN64=1 -DHAVE_LSEEK64=1 -DHAVE_TYPE_OFF64_T=1 -DHAVE_GETCWD=1 -DHAVE_OPENDIR=1 -DHAVE_STRTOL=1 -DHAVE_WAITPID=1 -DNO_GETWD=1 -DHAVE_GETADDRINFO=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_GMTIME_R=1 -DHAVE_LOCALTIME_R=1 -DHAVE_MKTIME=1 -DHAVE_TM_GMTOFF=1 -DHAVE_TIMEZONE_VAR=1 -DHAVE_STRUCT_STAT_ST_BLOCKS=1 -DHAVE_STRUCT_STAT_ST_BLKSIZE=1 -DHAVE_BLKCNT_T=1 -DHAVE_INTPTR_T=1 -DHAVE_UINTPTR_T=1 -DHAVE_SIGNED_CHAR=1 -DHAVE_LANGINFO=1 -DHAVE_SYS_IOCTL_H=1 -DTCL_UNLOAD_DLLS=1 -DTCL_CROSS_COMPILE=1 -I/home/steward/Downloads/openmsx-0.9.1/derived/mipsel-dingux-opt-3rd/3rdparty/install/include
TCL_LDFLAGS:=/home/steward/Downloads/openmsx-0.9.1/derived/mipsel-dingux-opt-3rd/3rdparty/install/lib/libtcl8.5.a -ldl
HAVE_XML_H:=true
HAVE_XML_LIB:=true
XML_CFLAGS:=-I/home/steward/Downloads/openmsx-0.9.1/derived/mipsel-dingux-opt-3rd/3rdparty/install/include/libxml2 -DLIBXML_STATIC
XML_LDFLAGS:=derived/mipsel-dingux-opt-3rd/3rdparty/install/lib/libxml2.a -lz
HAVE_ZLIB_H:=true
HAVE_ZLIB_LIB:=true
ZLIB_CFLAGS:=
ZLIB_LDFLAGS:=-lz
