#ifndef _JUEGO_IDIOMA_
#define _JUEGO_IDIOMA_

    const char *TESC_Juego::ia_txt_sp[]=
    {
        "INSTRUCCIONES",
        "ACERCA DE",
        "JUGAR",
        "SALIR DEL JUEGO",
		#if defined (TARGET_WII) || defined (TARGET_GP2X)
		"", 
		#else
        "(CTRL)(RET): VENTANA - PANTALLA",
		#endif
        "(ESC) SALIR DEL JUEGO",

        "PULSE: IZQUIERDA",
        "PULSE: DERECHA",
        "PULSE: SALTO LARGO",
        "PULSE: SALTO CORTO",
        "PULSE: ABORTAR PARTIDA",
        "PANTALLAS -",
        "VIDAS -",
        "CONTRASEÑA",
        
        "-*-",
        "[rainbow]",
        "ABUSIMBEL PROFANATION",
        "*********************",
        "",
        "VERSION ORIGINAL SPECTRUM",
        "REALIZADA POR:",
        "[rainbow]",
        "VICTOR RUIZ",
        "",
        "VERSION AMIGA, PC Y WII:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "[rainbow]",
        "RAUL HEREDIA FARFAN",
        "",
        "[rainbow]",
        "VERSION DELUXE",
        "**************",
        "",
        "PROGRAMACION:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "",
        "GRAFICOS:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "[rainbow]",
        "RAUL HEREDIA FARFAN",
        "[rainbow]",
        "BENITO NEMESIO CUBELLS",
        "",
        "MUSICA:",
        "[rainbow]",
        "ALEX BELENCOSO",
        "",
        "TRADUCCION:",
        "[rainbow]",
        "GREGORIO GUERRERO",
        "[rainbow]",
        "ALEX BELENCOSO",
        "[rainbow]",
        "SANDRA TROYANO MORALES",
        "",
        "",
        "",
        "-*-",
        "DESCUBRE EL SECRETO DE",
        "ABUSIMBEL PARA LIBERAR A",
        "JOHNY JONES DEL MALEFICIO.",
        "",
        "Y RECUERDA LAS DOS LEYENDAS",
        "QUE SOBRE EL TEMPLO DE",
        "ABUSIMBEL NOS DEJARON LOS",
        "ANTIGUOS LIBROS....",
        "",
        "'ESPERA, CALCULA Y",
        "PIENSA ANTES DE ACTUAR...'",
        "PROVERBIOS EGIPCIONES. CAP.XXII",
        "",
        "'EL DIAMANTE TE MOSTRARA",
        "EL CAMINO...'",
        "",
        "TEMPLOS PERDIDOS. CAP.IX.PG.6",
        "",
        "",
        "",
        "",
        "",
        "-*-",
        "MISION CUMPLIDA JOHNES. STOP.",
        "LA FRASE SECRETA",
        "DE ABUSIMBEL ES:",
        "'NOS VEREMOS EN EL POLO'. STOP.",
        "-*-"
    };

    const char *TESC_Juego::ia_txt_en[]=
    {
        "INSTRUCTIONS",
        "ABOUT",
        "PLAY",
        "EXIT GAME",
		#if defined (TARGET_WII) || defined (TARGET_GP2X)
		"",
		#else
        "(CTRL)(RET): WINDOW-FULLSCREEN",
		#endif
        "(ESC) EXIT GAME",
 
        "PRESS: LEFT",
        "PRESS: RIGHT",
        "PRESS: LONG JUMP",
        "PRESS: SHORT JUMP",
        "PRESS: ABORT GAME",
        "SCREENS -",
        "LIVES -",
        "PASSWORD",
        
        "-*-",
        "[rainbow]",
        "ABUSIMBEL PROFANATION",
        "*********************",
        "",
        "SPECTRUM ORIGINAL VERSION",
        "MADE BY:",
        "[rainbow]",
        "VICTOR RUIZ",
        "",
        "AMIGA, PC AND WII VERSION:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "[rainbow]",
        "RAUL HEREDIA FARFAN",
        "",
        "[rainbow]",
        "DELUXE VERSION",
        "**************",
        "",
        "CODE:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "",
        "GRAPHICS:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "[rainbow]",
        "RAUL HEREDIA FARFAN",
        "[rainbow]",
        "BENITO NEMESIO CUBELLS",
        "",
        "MUSIC:",
        "[rainbow]",
        "ALEX BELENCOSO",
        "",
        "TRANSLATION:",
        "[rainbow]",
        "GREGORIO GUERRERO",
        "[rainbow]",
        "ALEX BELENCOSO",
        "[rainbow]",
        "SANDRA TROYANO MORALES",
        "",
        "",
        "",
        "-*-",
        "DISCOVER THE SECRET OF",
        "ABUSIMBEL TO FREE",
        "JOHNY JONES FROM HIS",
        "ENCHANTMENT.",
        "",
        "AND REMEMBER THE TWO LEGENDS",
        "THAT ANCIENT BOOKS ",
        "LEFT US ABOUT ",
        "ABUSIMBEL TEMPLE....",
        "",
        "'WAIT, CALCULATE AND",
        "THINK BEFORE ACTING...'",
        "EGYPTION PROVERBS CHAP.XXII",
        "",
        "'THE DIAMOND WILL SHOW YOU",
        "THE WAY...'",
        "",
        "LOST TEMPLES CHAP.IX.PG.6",
        "",
        "",
        "",
        "",
        "",
        "-*-",
        "MISSION ACCOMPLISHED",
        "JOHNES. STOP.",
        "ABUSIMBEL'S SECRET CODE IS:",
        "'SEE YOU ON THE POLE'. STOP.",
        "-*-"
    };

    const char *TESC_Juego::ia_txt_fr[]=
    {
        "INSTRUCTIONS",
        "À PROPOS",
        "JOUER",
        "QUITTER LES JEUX",
		#if defined (TARGET_WII) || defined (TARGET_GP2X)
		"",
		#else
        "(CTRL)(RET): FENÊTRE - ÉCRAN",
		#endif
        "(ESC) QUITTER LES JEUX",
 

        "APPUYER SUR: GAUCHE",
        "APPUYER SUR: DROITTE",
        "APPUYER SUR: LONG SAUT",
        "APPUYER SUR: SAUT COURT",
        "APPUYER SUR: FINIR JEUX",
        "ÉCRANS -",
        "VIES -",
        "MOT DE PASSE",

        "-*-",
        "[rainbow]",
        "ABUSIMBEL PROFANATION",
        "*********************",
        "",
        "VERSION ORIGINALE SPECTRUM",
        "REALISÉE PAR:",
        "[rainbow]",
        "VICTOR RUIZ",
        "",
        "VERSION AMIGA, PC ET WII:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "[rainbow]",
        "RAUL HEREDIA FARFAN",
        "",
        "[rainbow]",
        "VERSION DELUXE",
        "**************",
        "",
        "PROGRAMMATION:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "",
        "GRAPHIQUES:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "[rainbow]",
        "RAUL HEREDIA FARFAN",
        "[rainbow]",
        "BENITO NEMESIO CUBELLS",
        "",
        "MUSIQUE:",
        "[rainbow]",
        "ALEX BELENCOSO",
        "",
        "TRADUCTION:",
        "[rainbow]",
        "GREGORIO GUERRERO",
        "[rainbow]",
        "ALEX BELENCOSO",
        "[rainbow]",
        "SANDRA TROYANO MORALES",
        "",
        "",
        "",
        "-*-",
        "DÉCOUVRE LE SECRET DE",
        "ABUSIMBEL POUR LIBÉRER",
        "JOHNY JONES DU MALÉFICE.",
        "",
        "ET RAPPELLES-TOI DES",
        "DEUX LÉGENDES",
        "QUE SUR LE TEMPLE DE",
        "ABUSIMBEL ON LAISSAIENT",
        "LES ANCIENS LIVRES....",
        "",
        "'ATTENDS, CALCULES ET",
        "PENSE AVANT D'AGIR...'",
        "'PROVERBES ÉGYPTIENS'",
        "CHAP.XXII",
        "",
        "'LE DIAMANT TE MONTRERA",
        "LE CHEMIN...'",
        "",
        "'TEMPLES PERDUS'",
        "CHAP.IX.PG.6",
        "",
        "",
        "",
        "",
        "",
        "-*-",
        "MISSION ACCOMPLIE JONES. STOP.",
        "LA PHRASE SECRÈTE DE",
        "ABUSIMBEL C'EST:",
        "'ON SE VOIT AU PÔLE'. STOP.",
        "-*-"
    };

    const char *TESC_Juego::ia_txt_de[]=
    {
        "ANWSEISUNGEN",
        "ÜBER",
        "SPIELEN",
        "ESCAPE",
		#if defined (TARGET_WII) || defined (TARGET_GP2X)
		"",
		#else
        "CTRL. RET. FENSTER - SCHIRM",
		#endif
        "ESC. ESCAPE",

        "SCHLAGE: LINKS",
        "SCHLAGE: RECHTS",
        "SCHLAGE: GROSSER SPRING",
        "SCHLAGE: KURZER SPRING",
        "SCHLAGE: ABORT SPIELE",
        "SCHIRME -",
        "LEBEN -",
        "PASSWORD",
        "-*-",
        "[rainbow]",
        "ABUSIMBEL LAIE",
        "**************",
        "",
        "ORIGINAL FASSUNG",
        "AUSGEFÜHRT VON:",
        "[rainbow]",
        "VICTOR RUIZ",
        "",
        "FASSUNG AMIGA, PC UND WII.",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "[rainbow]",
        "RAUL HEREDIA FARFAN",
        "",
        "[rainbow]",
        "DELUXE FASSUNG",
        "**************",
        "",
        "PROGRAMMIERUNG:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "",
        "GRAFISCHE DARSTELLUNGEN:",
        "[rainbow]",
        "M. ANGEL JIMENEZ SANTANA",
        "[rainbow]",
        "RAUL HEREDIA FARFAN",
        "[rainbow]",
        "BENITO NEMESIO CUBELLS",
        "",
        "MUSIK:",
        "[rainbow]",
        "ALEX BELENCOSO",
        "",
        "TRANSLATION:",
        "[rainbow]",
        "GREGORIO GUERRERO",
        "[rainbow]",
        "ALEX BELENCOSO",
        "[rainbow]",
        "SANDRA TROYANO MORALES",
        "",
        "",
        "",
        "-*-",
        "ENTDECKE DAS GEHEIMNIS VON",
        "ABUSIMBEL UM JEMANDEN ZU",
        "BEFREIEN JOHNY JONES",
        "VOM ZAUBER",
        "",
        "UND ERINERE DICH AN DIE",
        "ZWEI LEGENDEN, DASS",
        "DIE ALTEN BÜCHER UNS AUF",
        "DEM TEMPEL VON",
        "ABUSIMBEL LIESSEN",
        "",
        "'WARTE UND RECHNE UND DENKE",
        "BEVOR DU ETWAS TUST'",
        "",
        "EGYPTISCHE SPRICHWÖRTER,",
        "KAPITEL XXII",
        "",
        "'DAS DIAMANT WIRD",
        "DIR DEN WEG'",
        "ZEIGEN, KAPITEL IX, SEITE 6",
        "",
        "",
        "",
        "",
        "",
        "-*-",
        "ERFÜLLTE MISSION JOHNES. STOP",
        "DER GEHEIME SATZ VON",
        "ABUSIMBEL IST: 'WIR WERDEN",
        "UNS IM POL SEHEN'. STOP",
        "-*-"
    };

#endif
