all:
	mipsel-linux-gcc main.cpp -o ram_size -lSDL_image -lSDL -lSDL_ttf -I/home/steward/Github/gh_retrogame_toolchain/for_os/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL
	#gcc main.cpp -g -o ram_size -DDEBUG -lSDL_image -lSDL -lSDL_ttf -I/usr/include/SDL
clean:
	rm -rf ram_size
