# Configure Makefile for the SGE library

# Comment/uncomment the following line to disable/enable build options
# (See README for more info)
C_COMP = y
USE_FT = n
USE_IMG = n
#QUIET = y

# Use this to build 32-bit libs on 64-bit Linux systems
FORCE32 = n

# Compilers (C and C++)
CC=mipsel-linux-gcc
CXX=mipsel-linux-g++
ifeq ($(FORCE32), y)
	CC += -m32
	CXX += -m32
endif

# Make sure sdl-config is available
HAVE_SDL =$(shell if (/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/bin/sdl-config --version) < /dev/null > /dev/null 2>&1; then echo "y"; else echo "n"; fi;)
ifeq ($(HAVE_SDL),n)
  $(error ERROR: Can't find SDL! Make sure that you have SDL (http://www.libsdl.org/) and its development files installed)
endif

# Where should SGE be installed?
PREFIX =$(shell /home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/bin/sdl-config --prefix)

# Where should the headerfiles be installed?
PREFIX_H =$(shell /home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/bin/sdl-config --prefix)/include/SDL

# Flags passed to the compiler
CFLAGS =-Wall -O3 -ffast-math
SGE_CFLAGS =$(shell /home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/bin/sdl-config --cflags)
# Uncomment to make some more optimizations
#CFLAGS =-Wall -O9 -ffast-math -march=i686


# Libs config
SGE_LIBS =$(shell /home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/bin/sdl-config --libs) -lstdc++


# Is freetype-config available?
HAVE_FT =$(shell if (/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/bin/freetype-config --version) < /dev/null > /dev/null 2>&1; then echo "y"; else echo "n"; fi;)
ifeq ($(HAVE_FT),n)
  USE_FT = n
endif

ifneq ($(USE_FT),n)
  USE_FT = y
  SGE_LIBS +=$(shell /home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/bin/freetype-config --libs)
  FT_CFLAGS =$(shell /home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/bin/freetype-config --cflags)
endif


# Is SDL_image available?
HAVE_IMG =$(shell if test -e "`/opt/gcw0-toolchain/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/bin/sdl-config --prefix`/include/SDL/SDL_image.h" >/dev/null 2>&1; then echo "y"; else echo "n"; fi;)

ifneq ($(USE_IMG),y)
  ifneq ($(USE_IMG),n)
    USE_IMG =$(HAVE_IMG)
  endif
endif

ifeq ($(USE_IMG),y)
  SGE_LIBS +=-lSDL_image
endif

