# Automatically generated by build system.
# Non-empty value means found, empty means not found.
HAVE_AO_H:=true
HAVE_AO_LIB:=true
AO_CFLAGS:=
AO_LDFLAGS:=-lao
HAVE_PNG_H:=true
HAVE_PNG_LIB:=true
PNG_CFLAGS:=-I/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/libpng16
PNG_LDFLAGS:=-L/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib -lpng16
HAVE_SDL_H:=true
HAVE_SDL_LIB:=true
SDL_CFLAGS:=-I/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
SDL_LDFLAGS:=-L/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib -lSDL -lpthread
HAVE_SDL_TTF_H:=true
HAVE_SDL_TTF_LIB:=true
SDL_TTF_CFLAGS:=-I/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/freetype2
SDL_TTF_LDFLAGS:=-lSDL_ttf
HAVE_TCL_H:=
HAVE_TCL_LIB:=
TCL_CFLAGS:=
TCL_LDFLAGS:=
HAVE_XML_H:=
HAVE_XML_LIB:=
XML_CFLAGS:=-I/usr/include/libxml2 -DLIBXML_STATIC
XML_LDFLAGS:=-lxml2
HAVE_ZLIB_H:=true
HAVE_ZLIB_LIB:=true
ZLIB_CFLAGS:=
ZLIB_LDFLAGS:=-lz
